server:
  port: 8200

map-server:
  init-dirs:  map, map/google, map/google/satellite, map/google/image, map/google/terrain, map/amap, map/amap/satellite, map/amap/image, map/amap/cover, map/tianditu, map/tianditu/satellite, map/tianditu/image, map/tianditu/cover
  config-file: map/map.config.json

# 日志配置
logging:
  level:
    com.cheese.MapServer: debug
    org.springframework: warn
